fmod PEANO is
sort PeanoNat .
op 0 : -> PeanoNat [ctor] .
op s : PeanoNat -> PeanoNat [ctor] .
vars N M : PeanoNat .
op _+_ : PeanoNat PeanoNat -> PeanoNat [assoc comm] .
*** Caso 1: constructor 0
eq [s1] : 0 + N = N .
*** Caso 2: constructor sucesor
eq [s2] : s(N) + M = s(N + M) .
op _*_ : PeanoNat PeanoNat -> PeanoNat [assoc comm] .
eq 0 * N = 0 .
eq s(N) * M = M + (N * M) .
op esPositivo : PeanoNat -> Bool .
eq esPositivo(0) = false .
eq esPositivo(s(N)) = true .
endfm
