# Generated by Django 5.0.2 on 2024-03-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0002_chat_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='cod_modulo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
