# Generated by Django 5.0.2 on 2024-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0003_chat_cod_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='cod_modulo',
            field=models.TextField(default=''),
        ),
    ]
