# Generated by Django 5.0.3 on 2024-04-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0006_modulomaude'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuloMaude',
            new_name='Modulo',
        ),
    ]
