# Generated by Django 5.0.3 on 2024-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0007_rename_modulomaude_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='modulos_maude', verbose_name='Imagen del Módulo'),
        ),
    ]
