# Generated by Django 5.0.2 on 2024-08-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0009_moduloversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduloversion',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='Proyecto1.chat'),
        ),
    ]
