# Generated by Django 5.0.2 on 2024-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0012_mensaje_titulo_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
