# Generated by Django 5.0.2 on 2024-08-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0015_entrega_remitente_entrega_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='corregido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrega',
            name='nota',
            field=models.TextField(blank=True, null=True, verbose_name='Nota del Administrador'),
        ),
    ]
