# Generated by Django 5.0.2 on 2024-08-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0017_rename_fecha_entrega_entrega_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='entrega',
            name='mensajes',
            field=models.ManyToManyField(to='Proyecto1.mensaje'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='titulo',
            field=models.CharField(default='Nombre título default', max_length=255, verbose_name='Título de la Entrega'),
        ),
    ]
