# Generated by Django 5.0.2 on 2024-08-22 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto1', '0018_remove_entrega_mensaje_entrega_mensajes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
